:queues:
  - [tasks, 2]
  - default
:schedule:
  update_tasks_job:
    every: ["8s"] # every 8 seconds
    queue: tasks
    class: "UpdateTasksJob"

  update_computers_job:
    every: ["30s"] # every 30 seconds
    queue: default
    class: "UpdateComputersJob"